//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CiviKey.Models
{
    public partial class tContact
    {
        public tContact()
        {
            this.tContactRelations = new HashSet<tContactRelation>();
            this.tContactRelations1 = new HashSet<tContactRelation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LogoPath { get; set; }
    
        public virtual ICollection<tContactRelation> tContactRelations { get; set; }
        public virtual ICollection<tContactRelation> tContactRelations1 { get; set; }
    }
    
}
