//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CiviKey.Models
{
    public partial class tContactRelation
    {
        public tContactRelation()
        {
            this.tParticipations = new HashSet<tParticipation>();
        }
    
        public int Id { get; set; }
        public int ContactId { get; set; }
        public int EntityId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual tContact tContact { get; set; }
        public virtual tContact tContact1 { get; set; }
        public virtual ICollection<tParticipation> tParticipations { get; set; }
    }
    
}
