//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CiviKey.Models
{
    public partial class tFeature
    {
        public tFeature()
        {
            this.tDemoes = new HashSet<tDemo>();
            this.tSections = new HashSet<tSection>();
            this.tCategories = new HashSet<tCategory>();
            this.tParticipations = new HashSet<tParticipation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Ver { get; set; }
        public string Progress { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<tDemo> tDemoes { get; set; }
        public virtual ICollection<tSection> tSections { get; set; }
        public virtual ICollection<tCategory> tCategories { get; set; }
        public virtual ICollection<tParticipation> tParticipations { get; set; }
    }
    
}
