//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CiviKey.Models
{
    public partial class tFeature
    {
        public tFeature()
        {
            this.tSections = new HashSet<tSection>();
            this.tVideos = new HashSet<tVideo>();
            this.tCategories = new HashSet<tCategory>();
            this.tParticipations = new HashSet<tParticipation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public int Progress { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int IdRoadMap { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<tSection> tSections { get; set; }
        public virtual ICollection<tVideo> tVideos { get; set; }
        public virtual ICollection<tCategory> tCategories { get; set; }
        public virtual ICollection<tParticipation> tParticipations { get; set; }
        public virtual tRoadMap tRoadMap { get; set; }
    }
    
}
