//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CiviKey.Models
{
    public partial class tReleaseNote
    {
        public int Id { get; set; }
        public int RoadmapId { get; set; }
        public int RevisionNumber { get; set; }
        public string HtmlContent { get; set; }
        public System.DateTime ReleaseDate { get; set; }
    
        public virtual tRoadMap tRoadMap { get; set; }
    }
    
}
