//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CiviKey.Models
{
    public partial class tVideo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string VideoSource { get; set; }
        public int FeatureId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual tFeature tFeature { get; set; }
    }
    
}
